# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b7fcffcd073763ad331fce01b7ee965c170ae49422c0bd5dde3d010f71ea568e440a50f9f2702b6df05cc416512fe11a331b8c6b522a101059108be5a0910ed

test:
  secret_key_base: 67256d1b52a34b7278fb4eee52ba75e735ead702a5a452c4f7946ef9ecd3751c1fc80f64122abc4673681b2f21ecd4e32e733f0a31ae973d56f60539dff37cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
